### ISSUE TITLE
Download del listado de clientes y ordenes

### ISSUE THREAD

**Issue by dmorfav** [juanitourquiza/amalia#18]
Descargar el un fichero csv el listado de los clientes y el de las ordenes.

**Comment by dmorfav** [comment]
@juanitourquiza  Las entidades de [Users](https://github.com/juanitourquiza/amalia/blob/master/src/BackendBundle/Entity/Users.php) y la de [Orders](https://github.com/juanitourquiza/amalia/blob/master/src/BackendBundle/Entity/Orders.php) tienen varios campos. Cuales desea que sean exportables en el fichero csv??

**Comment by juanitourquiza** [comment]
Todos que sean exportables luego el cliente defina en el excel que columna no utilizará

**Comment by juanitourquiza** [comment]
Cliente solicita todos los campos de la orden. Completa eso por favor.

**Comment by dmorfav** [comment]
Resuelto en el commit bb29d29583a06546783d14b3c152d642fa4b0e52
