### ISSUE TITLE
Error en mode vacation

### ISSUE THREAD

**Issue by juanitourquiza** [juanitourquiza/amalia#21]
Fui a probar cambie el texto y  me dio este error
Ver las 2 fotos

<img width="663" alt="imagen" src="https://user-images.githubusercontent.com/332299/74989797-6db45980-540f-11ea-9b1f-bddf81c07af5.png">

<img width="629" alt="imagen" src="https://user-images.githubusercontent.com/332299/74989757-56756c00-540f-11ea-9cef-3f98e9c4735b.png">

**Comment by dmorfav** [comment]
resuelto en el commit 98a8a7ad7935dcf0b92bd3fa42a31458d3c789a4

**Comment by juanitourquiza** [comment]
Acaba de probar el cliente me indica lo siguiente:

<img width="675" alt="imagen" src="https://user-images.githubusercontent.com/332299/79798088-0e46cd00-831e-11ea-9c4b-922e09633fb9.png">

**Comment by dmorfav** [comment]
Acabo de probar el vacation Mode.
Cuando se activa se ve de la siguiente forma:
![Captura de pantalla de 2020-04-20 19-13-56](https://user-images.githubusercontent.com/10134910/79808987-6214de80-833d-11ea-9154-3920717d81aa.png)
Cuando se desactiva se ve asi:
![Captura de pantalla de 2020-04-20 19-15-16](https://user-images.githubusercontent.com/10134910/79809036-79ec6280-833d-11ea-9b77-e889f529d8f1.png)
Al parecer, algun elemento div se queda sin cerrarse, lo corrijo y lo subo. En caso de ser algo mas por favor confirmar con el cliente

**Comment by dmorfav** [comment]
Corregido lo que le comento anteriormente en 06a3fb8333c474512d69626838e332561b1fdc13

**Comment by juanitourquiza** [comment]
Se debe corregir que hay texto en ingles y español. Todo debe estar en ingles.
<img width="640" alt="imagen" src="https://user-images.githubusercontent.com/332299/79810595-03e5fc80-8339-11ea-9589-e56d2cf22780.png">

Ya con eso quedaria bien parece.
