### ISSUE TITLE
amalia problemas en el email de confirmacion

### ISSUE THREAD

**Issue by juanitourquiza** [juanitourquiza/amalia#22]
Esta es la confirmacion d ela orden las fotos no se ven

1-El logo arriba no sale

2-el discount code sale con” undefine” si no hay un discount code no deberia salir nada

3- el sales tax lo calculo pero  no salio  en el email

4-Puse una nota para la tarjeta de regalo y la nota no salio en adicional note

5- no mando copia a info@amaliajewelry.com

**Comment by dmorfav** [comment]
Resuelto en el commit bcbc99f4dc62400313221cec50a781606acc5b2b

**Comment by juanitourquiza** [comment]
Falta esto:
los item codes no salen en el email, tampoco sale  el tray number
hay que agregarselo

**Comment by dmorfav** [comment]
Corregido en el commit df49ad0fb5e01aa76bd3baa02536edcee2f917bf
