### ISSUE TITLE
Cambiar precios de no assembies

### ISSUE THREAD

**Issue by juanitourquiza** [juanitourquiza/amalia#23]
un area que corra un reporte de no assemblies  y assemblis items y que me permita cambiar los precios manualmente

O sea un area donde pueda filtrar por assemblies , no assemblies(stock items) y luego filtar por categorias y sub categorias y  items

Y me permita cambiar el precio manual o por % o sea ponga +5 increementa 5% a todo el rango escogido y luego un boton para confirmar y salvar el cambio

**Comment by dmorfav** [comment]
En que tabla específicamente se debe realizar las operaciones?

**Comment by dmorfav** [comment]
OK si entras en el Product List vas a ver en cualquier item en la mitad el component ID
La calculadora de gramos que armastes debe de trabajar soio con los Assembly (por favor revisa que sea asi)

 

Necesitamos hacer un area para modificar los precios   de cualquier tipo de ComponentiD para los Teresa y Retail

 

Creas un search con filtro  segun ComponentID/categorias/ subcategories/ o por palabra,  una vez crea el reporte  permitir cambiar los precios retail   y Teresa via % + o - (  uno para cada columna) , pones un boton para generas la lista modificada de precios y luego un boton para salvarla

Avisame si me entendistes o tienes una pregunta

**Comment by juanitourquiza** [comment]
Estoy tratando de hacer un search y no funciona

Primero  puse active all

Category pendants

No sale nada

 

Luego puse

Earrings

Category screwback only gold

active all

 

No sale nada

 

Luego puse earrings

active all

salen brazaletes y collares

 

 

luego a ese resultado de earrings que salio brazaletes puse 5% para Teresa y 5% para retail y me pregunta si quiero hacer el cambio

 

Eso no es lo que te pedi

Te pedi que muestres el cambio y luego un boton para aprobar

No quiero hacer un cambio si verlo antes

Tambien falta que redonde los decimales al proximo numero ejemplo

Si sube a 23.51 sera 24 si esta eb 3.49 seria 23

 

Por favor PRIMERO ARREGLA TODO EL SEACH QUE NO ESTA FUNCIONANDO Y REVISA QUE FUNCIONE TODAS LAS OPCIONES DE SEARCH

Luego arregla lo del cambio de precio QUE ME MUESTRE ANTES DE ACTUALIZAR

**Comment by dmorfav** [comment]
Resuelto en 7161544f3eeebbd491e82fd178c5e04712cdef2f

**Comment by juanitourquiza** [comment]
El search sigue sin funcionar cuando se convina opciones. Funciona cuando se selecciona una categoria pero se selecciona una subcategoria y ya no muestra nada.

**Comment by juanitourquiza** [comment]
En la busqueda como indicas debemos definir que campos son prioritarios o como definir el AND y el OR. Adjunto te envio el codigo fuente donde esta el where del sitio actual para esa busqueda-

El itemID y el descripcion deberia ser un like para la busqueda.

<img width="416" alt="imagen" src="https://user-images.githubusercontent.com/332299/78951095-7d0e6580-7a96-11ea-9efc-2f269894ae3b.png">

Si hace una busqueda por estas opciones de ItemNumber son un AND

<img width="839" alt="imagen" src="https://user-images.githubusercontent.com/332299/78951122-97484380-7a96-11ea-9c85-a3a99e7463e2.png">

La opcion de ACTIVE debe ser **obligatorio** en el WHERE con la opcion que seleccione.

<img width="308" alt="imagen" src="https://user-images.githubusercontent.com/332299/78951152-b7780280-7a96-11ea-84cb-b4c133cbc673.png">

Collection debe ser un OR

<img width="441" alt="imagen" src="https://user-images.githubusercontent.com/332299/78951175-c8c10f00-7a96-11ea-9c53-2056149b3c30.png">

Todos estas opciones deben ser un AND en el WHERE.

<img width="502" alt="imagen" src="https://user-images.githubusercontent.com/332299/78951226-fc039e00-7a96-11ea-97fa-f2ccb5e6a630.png">


[amalia.txt](https://github.com/juanitourquiza/amalia/files/4459256/amalia.txt)

**Comment by dmorfav** [comment]
Esto que me comenta ya esta resuelto, ahora tenemos otra situaci\'on, usted solicit\'o que si escojo una categor\'ia las subcategorias sean las que esten asignadas a esta. Si se dan estos escenarios que le dejo en las capturas que hacemos?
![2cat 1subcat](https://user-images.githubusercontent.com/10134910/79362147-3a281400-7f14-11ea-9cc0-e48c387932f7.png)
![2cat 3subcat](https://user-images.githubusercontent.com/10134910/79362200-4a3ff380-7f14-11ea-8c56-7cffe096b608.png)

**Comment by juanitourquiza** [comment]
Me indicas esto: "Es que cuando escoge 1 categoría no se si automáticamente debe seleccionar una subcategoria"
Podria ser que si pero y si solo quiere buscar por categorias?

**Comment by dmorfav** [comment]
> Me indicas esto: "Es que cuando escoge 1 categoría no se si automáticamente debe seleccionar una subcategoria"
> Podria ser que si pero y si solo quiere buscar por categorias?

Así mismo, entonces lo que me solicito de anclar las subcategorias a las categorías no debe ser así

**Comment by juanitourquiza** [comment]
Si debe ser pero tambien se puede dar la opcion que indique , "ALL" o todos .... Entonces por defecto se puede atar a la "subcategoria ALL" que en forme el where sin ninguna subcategoria especifica y haga solo la busqueda por categoria.

Se entiende?

**Comment by dmorfav** [comment]
Culminado su pedido en 4f135d77c70d2977363cb6e3afe7b6170708b14f
