### ISSUE TITLE
Filtros de busqueda en productlist (esto lo hizo Juan) no funciona

### ISSUE THREAD

**Issue by juanitourquiza** [juanitourquiza/amalia#25]
Realiza la busqueda por todos los items pero ekl momento de escoger categoria o subcategoria no busca nada.
https://34.230.134.197/admin/productlist

<img width="657" alt="imagen" src="https://user-images.githubusercontent.com/332299/74990091-4a3dde80-5410-11ea-8b28-c7a7c71c6574.png">

**Comment by dmorfav** [comment]
Corregido en 66becb6b19caa45a2edc8aa363647771a97406cb

**Comment by juanitourquiza** [comment]
El campo active esta al reves, si coloco NO ..... salen todos los archivos. 
<img width="478" alt="imagen" src="https://user-images.githubusercontent.com/332299/79761030-8b565000-82e6-11ea-892d-7d9fa8dfeb7a.png">

Si coloco los archivos en YES sale uno en este ejemplo eso se debe corregir.
Esta validacion que esta al reves.

<img width="304" alt="imagen" src="https://user-images.githubusercontent.com/332299/79761293-d708f980-82e6-11ea-8063-cddb246b8f9e.png">

**Comment by dmorfav** [comment]
Realizado el cambio
